import { t } from '@superset-ui/core';

interface TimezoneDataProps {
  label: string;
  value: string;
}
const DvtTimezoneData: TimezoneDataProps[] = [
  { label: 'GMT +01:00 (Central European Time)', value: 'Europe/Andorra' },
  { label: 'GMT +04:00 (Asia/Dubai)', value: 'Asia/Dubai' },
  { label: 'GMT +04:00 (Asia/Dubai)', value: 'Asia/Dubai' },
  { label: 'GMT +04:30 (Asia/Kabul)', value: 'Asia/Kabul' },
  { label: 'GMT +04:30 (Asia/Kabul)', value: 'Asia/Kabul' },
  { label: 'GMT -04:00 (America/Antigua)', value: 'America/Antigua' },
  { label: 'GMT +01:00 (Africa/Lagos)', value: 'Africa/Lagos' },
  { label: 'GMT +11:00 (Antarctica/Casey)', value: 'Antarctica/Casey' },
  { label: 'GMT +07:00 (Antarctica/Davis)', value: 'Antarctica/Davis' },
  {
    label: 'GMT +10:00 (Antarctica/DumontDUrville)',
    value: 'Antarctica/DumontDUrville',
  },
  { label: 'GMT +05:00 (Antarctica/Mawson)', value: 'Antarctica/Mawson' },
  { label: 'GMT +13:00 (Antarctica/McMurdo)', value: 'Antarctica/McMurdo' },
  { label: 'GMT -03:00 (Antarctica/Palmer)', value: 'Antarctica/Palmer' },
  { label: 'GMT +03:00 (Antarctica/Syowa)', value: 'Antarctica/Syowa' },

  { label: 'GMT +00:00 (Antarctica/Troll)', value: 'Antarctica/Troll' },
  { label: 'GMT +06:00 (Antarctica/Vostok)', value: 'Antarctica/Vostok' },
  { label: 'GMT -11:00 (Pacific/Pago_Pago)', value: 'Pacific/Pago_Pago' },
  { label: 'GMT +11:00 (Antarctica/Macquarie)', value: 'Antarctica/Macquarie' },
  { label: 'GMT +10:30 (Australia/Adelaide)', value: 'Australia/Adelaide' },
  { label: 'GMT +09:30 (Australia/Darwin)', value: 'Australia/Darwin' },
  { label: 'GMT +08:45 (Australia/Eucla)', value: 'Australia/Eucla' },
  { label: 'GMT +11:00 (Australia/Lord_Howe)', value: 'Australia/Lord_Howe' },
  { label: 'GMT +08:00 (Australia/Perth)', value: 'Australia/Perth' },
  { label: 'GMT +02:00 (Europe/Helsinki)', value: 'Europe/Helsinki' },
  { label: 'GMT +00:00 (GMT Standard Time)', value: 'Africa/Abidjan' },
  { label: 'GMT +02:00 (Africa/Bujumbura)', value: 'Africa/Bujumbura' },
  { label: 'GMT -04:00 (Atlantic/Bermuda)', value: 'Atlantic/Bermuda' },
  { label: 'GMT -05:00 (America/Eirunepe)', value: 'America/Eirunepe' },
  { label: 'GMT -02:00 (America/Noronha)', value: 'America/Noronha' },
  { label: 'GMT -05:00 (Eastern Standard Time)', value: 'America/Nassau' },
  { label: 'GMT -06:00 (America/Belize)', value: 'America/Belize' },
  {
    label: 'GMT -07:00 (Mountain Standard Time)',
    value: 'America/Cambridge_Bay',
  },
  {
    label: 'GMT -07:00 (Mountain Standard Time - Phoenix)',
    value: 'America/Creston',
  },
  { label: 'GMT -06:00 (Central Standard Time)', value: 'America/Rainy_River' },
  { label: 'GMT -03:30 (America/St_Johns)', value: 'America/St_Johns' },
  { label: 'GMT -08:00 (Pacific Standard Time)', value: 'America/Vancouver' },
  { label: 'GMT +06:30 (Asia/Yangon)', value: 'Asia/Yangon' },
  { label: 'GMT -10:00 (Hawaii Standard Time)', value: 'Pacific/Rarotonga' },
  { label: 'GMT -03:00 (America/Santiago)', value: 'America/Santiago' },
  { label: 'GMT -05:00 (Pacific/Easter)', value: 'Pacific/Easter' },
  { label: 'GMT -01:00 (Atlantic/Cape_Verde)', value: 'Atlantic/Cape_Verde' },
  {
    label: 'GMT +00:00 (GMT Standard Time - London)',
    value: 'Atlantic/Canary',
  },
  { label: 'GMT +12:00 (Pacific/Fiji)', value: 'Pacific/Fiji' },
  { label: 'GMT -03:00 (America/Nuuk)', value: 'America/Nuuk' },
  { label: 'GMT -01:00 (America/Scoresbysund)', value: 'America/Scoresbysund' },
  { label: 'GMT +09:00 (Asia/Jayapura)', value: 'Asia/Jayapura' },
  { label: 'GMT +05:30 (Asia/Kolkata)', value: 'Asia/Kolkata' },
  { label: 'GMT +03:30 (Asia/Tehran)', value: 'Asia/Tehran' },
  { label: 'GMT +13:00 (Pacific/Kanton)', value: 'Pacific/Kanton' },
  { label: 'GMT +14:00 (Pacific/Kiritimati)', value: 'Pacific/Kiritimati' },
  { label: 'GMT +12:00 (Pacific/Norfolk)', value: 'Pacific/Norfolk' },
  { label: 'GMT +05:45 (Asia/Kathmandu)', value: 'Asia/Kathmandu' },
  { label: 'GMT +13:45 (Pacific/Chatham)', value: 'Pacific/Chatham' },
  { label: 'GMT -09:00 (Pacific/Gambier)', value: 'Pacific/Gambier' },
  { label: 'GMT -09:30 (Pacific/Marquesas)', value: 'Pacific/Marquesas' },
  { label: 'GMT -08:00 (Pacific/Pitcairn)', value: 'Pacific/Pitcairn' },
  { label: 'GMT -10:00 (America/Adak)', value: 'America/Adak' },
  { label: 'GMT -09:00 (Alaska Standard Time)', value: 'America/Anchorage' },
  { label: 'GMT +13:00 (Pacific/Apia)', value: 'Pacific/Apia' },
];
export { DvtTimezoneData };
